running into this this bug: https://bugs.openjdk.java.net/browse/JDK-8016914 ?
```
javax.xml.transform.TransformerException: java.lang.NullPointerException
  at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:737)
  ...
Caused by: java.lang.NullPointerException
  at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.setXmlVersion(CoreDocumentImpl.java:901)
  ...
```

```java
public static void main(String[] args) {
  try {
    String dir =
"C:/Users/Besitzer/openLCA-data-1.4/databases/example_kml";
    String kmlFile =
"C:/Users/Besitzer/Downloads/Geographies.xml/Geographies.xml";
    IDatabase db = new DerbyDatabase(new File(dir));
    KMLImport imp = new KMLImport(new File(kmlFile), db);
    imp.run();
  } catch (Exception e) {
    e.printStackTrace();
  }
}
```

-> now it works; but this was also an really important thing:

```java
factory.setNamespaceAware(true);
```