so, we first need to load the dependency graph of the sub-systems.
we will do this by scanning the process link table `tbl_process_links`
(not the `tbl_product_system_processes` as we may want to remove this):

```sql
CREATE TABLE tbl_process_links (

    f_product_system  BIGINT,
    f_provider        BIGINT,
    f_flow            BIGINT,
    f_process         BIGINT,
    f_exchange        BIGINT,
    is_system_link    SMALLINT default 0
);
```

... and we should avoid this when the product system has no sub-systems
... woah the initialization of this thing needs much more effort than
the running the simulation.

regarding a fast breadth-first search this is interesting:
https://www2.eecs.berkeley.edu/Pubs/TechRpts/2011/EECS-2011-117.pdf

this can be removed, as we need to collect the sub-system links before
we initialze the nodes:

```java
Set<ProcessProduct> subSystems() {
  if (_subSystems != null)
    return _subSystems;
  if (data == null || data.techIndex == null)
    return Collections.emptySet();
  _subSystems = new HashSet<>();
  data.techIndex.each((i, p) -> {
    if (p.process != null
        && p.process.type == ModelType.PRODUCT_SYSTEM) {
      _subSystems.add(p);
    }
  });
  return _subSystems;
}
```

Also, we can remove all the old initialization code (?)

```java
// collect and create the sub-system nodes
List<LongPair> subLinks = new ArrayList<>();
Queue<Node> q = new ArrayDeque<>();
q.add(g.root);
while (!q.isEmpty()) {
  Node n = q.poll();
  for (ProcessProduct pp : n.subSystems()) {
    long subSystemID = pp.id();
    subLinks.add(LongPair.of(subSystemID, n.systemID));
    if (g.nodeIndex.containsKey(subSystemID))
      continue
    // create node for LCI and LCC data simulation
    // do *not* copy the LCIA method here
    ProductSystemDao dao = new ProductSystemDao(
        mcache.getDatabase());
    ProductSystem sub = dao.getForId(subSystemID);
    CalculationSetup subSetup = new CalculationSetup(
        CalculationType.SIMPLE_CALCULATION, sub);
    subSetup.parameterRedefs.addAll(sub.parameterRedefs);
    subSetup.withCosts = setup.withCosts;
    subSetup.allocationMethod = setup.allocationMethod;
    Node subNode = g.makeNode(subSetup, mcache);
    g.nodeIndex.put(subNode.systemID, subNode);
    q.add(subNode);
  }

// create the topological order
List<Long> order = TopoSort.of(subLinks);
if (order == null)
  throw new RuntimeException(
      "there are sub-system cycles in the product system");
for (Long id : order) {
  if (id == g.root.systemID)
    continue;
  g.nodes.add(g.nodeIndex.get(id));

// for the sub-system links we have to set the values in the
// technology matrices
Consumer<Node> subLinkFn = (Node node) -> {
  for (ProcessProduct pp : node.subSystems()) {
    Node subNode = g.nodeIndex.get(pp.id());
    if (subNode == null)
      continue;
    int idx = node.data.techIndex.getIndex(pp);
    if (idx < 0)
      continue;
    node.data.techMatrix.set(
        idx, idx, subNode.data.techIndex.getDemand());
  }
};
for (Node node : g.nodes) {
  subLinkFn.accept(node);
}
subLinkFn.accept(g.root);
```

Lets check now the example:

```
org.apache.commons.math3.linear.SingularMatrixException: matrix is singular
```

ok, the debugger hangs, lets check some points:

* we may can make the sub-system link search faster when we filter the
  query by the field `is_system_link` -> we need to run some benchmarks

now it works but we do not get random numbers